<?php

   /* Image Defaults
   | We set the config here so that we can keep our controllers clean.
   | Configure each image type with an image path.
   | the empty space is intentional for the code generator.
   | first array key should start on line 20
   */

return [


    ['word' => 'accipiter', 'meaning' => 'hawk'],
    ['word' => 'acer', 'meaning' => 'maple'],
    ['word' => 'acerbissimus', 'meaning' => 'bitter'],
    ['word' => 'acervulus', 'meaning' => 'heap'],
    ['word' => 'acicula', 'meaning' => 'needle'],
    ['word' => 'adeps', 'meaning' => 'fat'],
    ['word' => 'aedes', 'meaning' => 'building'],
    ['word' => 'aemulus', 'meaning' => 'emulate'],
    ['word' => 'aequus', 'meaning' => 'level'],
    ['word' => 'aes', 'meaning' => 'ore'],
    ['word' => 'aestas', 'meaning' => 'summer'],
    ['word' => 'aevum', 'meaning' => 'age-eon'],
    ['word' => 'agrellus', 'meaning' => 'agricultural'],
    ['word' => 'alacrior', 'meaning' => 'quick'],
    ['word' => 'albior', 'meaning' => 'albino'],
    ['word' => 'alga', 'meaning' => 'seaweed'],
    ['word' => 'alius', 'meaning' => 'other'],
    ['word' => 'alveus', 'meaning' => 'alveus'],
    ['word' => 'amarus', 'meaning' => 'bitter'],
    ['word' => 'ambo', 'meaning' => 'both-ambiguous'],
    ['word' => 'amoenus', 'meaning' => 'amenity'],
    ['word' => 'ancilla', 'meaning' => 'ancillary'],
    ['word' => 'anguis', 'meaning' => 'snake'],
    ['word' => 'angulus', 'meaning' => 'angular'],
    ['word' => 'anima', 'meaning' => 'life'],
    ['word' => 'animus', 'meaning' => 'mind-anger'],
    ['word' => 'anser', 'meaning' => 'goose'],
    ['word' => 'apis', 'meaning' => 'bee'],
    ['word' => 'aquula', 'meaning' => 'water'],
    ['word' => 'arbor', 'meaning' => 'tree'],
    ['word' => 'arcus', 'meaning' => 'arc'],
    ['word' => 'arduus', 'meaning' => 'arduous'],
    ['word' => 'argentum', 'meaning' => 'silver'],
    ['word' => 'armus', 'meaning' => 'shoulder'],
    ['word' => 'articulus', 'meaning' => 'articulate'],
    ['word' => 'arvus', 'meaning' => 'plowed'],
    ['word' => 'asellus', 'meaning' => 'donkey'],
    ['word' => 'asper', 'meaning' => 'rough'],
    ['word' => 'astus', 'meaning' => 'astute'],
    ['word' => 'audax', 'meaning' => 'audacious'],
    ['word' => 'audacissimus', 'meaning' => 'brave-bold'],
    ['word' => 'auris', 'meaning' => 'ear'],
    ['word' => 'aurum', 'meaning' => 'gold'],
    ['word' => 'avena', 'meaning' => 'oat'],
    ['word' => 'aucella', 'meaning' => 'bird'],
    ['word' => 'avunculus', 'meaning' => 'uncle'],
    ['word' => 'baca', 'meaning' => 'berry'],
    ['word' => 'bacillum', 'meaning' => 'imbecile'],
    ['word' => 'baiulus', 'meaning' => 'carrier'],
    ['word' => 'barbula', 'meaning' => 'beard'],
    ['word' => 'bassus', 'meaning' => 'low'],
    ['word' => 'beatus', 'meaning' => 'blessed'],
    ['word' => 'bellum', 'meaning' => 'war'],
    ['word' => 'bellus', 'meaning' => 'pretty'],
    ['word' => 'bene', 'meaning' => 'good'],
    ['word' => 'bestia', 'meaning' => 'animal'],
    ['word' => 'bini', 'meaning' => 'two each'],
    ['word' => 'melior', 'meaning' => 'ameliorate'],
    ['word' => 'botellus', 'meaning' => 'sausage'],
    ['word' => 'bracchium', 'meaning' => 'support'],
    ['word' => 'brevis', 'meaning' => 'brief'],
    ['word' => 'bucca', 'meaning' => 'mouth'],
    ['word' => 'bursa', 'meaning' => 'pouch'],
    ['word' => 'caballus', 'meaning' => 'horse'],
    ['word' => 'calvus', 'meaning' => 'bald'],
    ['word' => 'calx', 'meaning' => 'pebble'],
    ['word' => 'camisia', 'meaning' => 'shirt'],
    ['word' => 'canis', 'meaning' => 'dog'],
    ['word' => 'canus', 'meaning' => 'grey'],
    ['word' => 'capanna', 'meaning' => 'cabin'],
    ['word' => 'capra', 'meaning' => 'goat'],
    ['word' => 'capellus', 'meaning' => 'goat'],
    ['word' => 'capillus', 'meaning' => 'hair'],
    ['word' => 'capsella', 'meaning' => 'box'],
    ['word' => 'capitellum', 'meaning' => 'head'],
    ['word' => 'cancelli', 'meaning' => 'jail'],
    ['word' => 'carduus', 'meaning' => 'card'],
    ['word' => 'carrum', 'meaning' => 'wheeled vehicle'],
    ['word' => 'cartilago', 'meaning' => 'cartilage'],
    ['word' => 'carissimus', 'meaning' => 'dear'],
    ['word' => 'caseus', 'meaning' => 'cheese'],
    ['word' => 'castrum', 'meaning' => 'castle'],
    ['word' => 'castior', 'meaning' => 'pure'],
    ['word' => 'catena', 'meaning' => 'chain'],
    ['word' => 'cauda', 'meaning' => 'tail'],
    ['word' => 'caulis', 'meaning' => 'stalk-stem'],
    ['word' => 'cavus', 'meaning' => 'hollow'],
    ['word' => 'celeber', 'meaning' => 'famous'],
    ['word' => 'celerior', 'meaning' => 'quick-swift'],
    ['word' => 'centeni', 'meaning' => 'hundred each'],
    ['word' => 'centesimus', 'meaning' => 'hundreth'],
    ['word' => 'centum', 'meaning' => 'hundred'],
    ['word' => 'cera', 'meaning' => 'wax'],
    ['word' => 'certus', 'meaning' => 'certain'],
    ['word' => 'cervus', 'meaning' => 'deer'],
    ['word' => 'ceterus', 'meaning' => 'other'],
    ['word' => 'cibus', 'meaning' => 'food'],
    ['word' => 'cicatrix', 'meaning' => 'scar'],
    ['word' => 'cilium', 'meaning' => 'eyelash'],
    ['word' => 'cinis', 'meaning' => 'ashes'],
    ['word' => 'cippus', 'meaning' => 'stake'],
    ['word' => 'circellus', 'meaning' => 'circle'],
    ['word' => 'cirrus', 'meaning' => 'curl-tentacle'],
    ['word' => 'citer', 'meaning' => 'on this side'],
    ['word' => 'citerior', 'meaning' => 'on this side'],
    ['word' => 'civis', 'meaning' => 'citizen'],
    ['word' => 'clarior', 'meaning' => 'clear'],
    ['word' => 'clavis', 'meaning' => 'key'],
    ['word' => 'collis', 'meaning' => 'hill'],
    ['word' => 'collum', 'meaning' => 'neck'],
    ['word' => 'columba', 'meaning' => 'dove'],
    ['word' => 'corculum', 'meaning' => 'heart'],
    ['word' => 'corbis', 'meaning' => 'basket'],
    ['word' => 'corium', 'meaning' => 'skin-hide'],
    ['word' => 'cornu', 'meaning' => 'horn'],
    ['word' => 'coruscus', 'meaning' => 'vibrate'],
    ['word' => 'corvus', 'meaning' => 'raven'],
    ['word' => 'corvellus', 'meaning' => 'raven'],
    ['word' => 'coxa', 'meaning' => 'hip'],
    ['word' => 'crassus', 'meaning' => 'thick'],
    ['word' => 'cratis', 'meaning' => 'crate'],
    ['word' => 'crena', 'meaning' => 'notch'],
    ['word' => 'creta', 'meaning' => 'chalk'],
    ['word' => 'cribrum', 'meaning' => 'sieve'],
    ['word' => 'crimen', 'meaning' => 'criminal'],
    ['word' => 'crinis', 'meaning' => 'hair'],
    ['word' => 'cucullus', 'meaning' => 'hood'],
    ['word' => 'culcita', 'meaning' => 'mattress'],
    ['word' => 'culex', 'meaning' => 'gnat'],
    ['word' => 'culina', 'meaning' => 'kitchen'],
    ['word' => 'culpa', 'meaning' => 'blame'],
    ['word' => 'cumulus', 'meaning' => 'heap'],
    ['word' => 'cunae', 'meaning' => 'cradle'],
    ['word' => 'cuneus', 'meaning' => 'wedge'],
    ['word' => 'cupella', 'meaning' => 'cup'],
    ['word' => 'cura', 'meaning' => 'care'],
    ['word' => 'currus', 'meaning' => 'chariot'],
    ['word' => 'curtus', 'meaning' => 'shortened'],
    ['word' => 'curvus', 'meaning' => 'bent-curved'],
    ['word' => 'cuspis', 'meaning' => 'tip'],
    ['word' => 'custos', 'meaning' => 'guardian'],
    ['word' => 'cutis', 'meaning' => 'hide-skin'],
    ['word' => 'decimus', 'meaning' => 'tenth'],
    ['word' => 'decus', 'meaning' => 'decor'],
    ['word' => 'deni', 'meaning' => 'ten each'],
    ['word' => 'densus', 'meaning' => 'thick'],
    ['word' => 'deus', 'meaning' => 'god'],
    ['word' => 'dextimus', 'meaning' => 'dexterity'],
    ['word' => 'dignus', 'meaning' => 'worthy'],
    ['word' => 'dirus', 'meaning' => 'dire'],
    ['word' => 'discipulus', 'meaning' => 'student'],
    ['word' => 'divus', 'meaning' => 'god'],
    ['word' => 'domus', 'meaning' => 'house'],
    ['word' => 'donum', 'meaning' => 'gift'],
    ['word' => 'dorsum', 'meaning' => 'back'],
    ['word' => 'dos', 'meaning' => 'dowry'],
    ['word' => 'drappus', 'meaning' => 'cloth'],
    ['word' => 'dulcis', 'meaning' => 'sweet'],
    ['word' => 'duodecimus', 'meaning' => 'twelfth'],
    ['word' => 'duplus', 'meaning' => 'twofold'],
    ['word' => 'durus', 'meaning' => 'hard'],
    ['word' => 'ebrius', 'meaning' => 'drunk'],
    ['word' => 'ensis', 'meaning' => 'sword'],
    ['word' => 'equus', 'meaning' => 'horse'],
    ['word' => 'eruca', 'meaning' => 'caterpillar'],
    ['word' => 'exterus', 'meaning' => 'outer'],
    ['word' => 'faba', 'meaning' => 'bean'],
    ['word' => 'faber', 'meaning' => 'fabric'],
    ['word' => 'faenum', 'meaning' => 'hay'],
    ['word' => 'fascis', 'meaning' => 'bundle'],
    ['word' => 'fauces', 'meaning' => 'throat'],
    ['word' => 'febris', 'meaning' => 'fever'],
    ['word' => 'felix', 'meaning' => 'happy'],
    ['word' => 'femina', 'meaning' => 'woman'],
    ['word' => 'fenestra', 'meaning' => 'window'],
    ['word' => 'ferox', 'meaning' => 'fierce'],
    ['word' => 'ferrum', 'meaning' => 'iron'],
    ['word' => 'ferus', 'meaning' => 'wild'],
    ['word' => 'festus', 'meaning' => 'festival'],
    ['word' => 'feudum', 'meaning' => 'fee'],
    ['word' => 'ficus', 'meaning' => 'fig'],
    ['word' => 'fides', 'meaning' => 'faith-trust'],
    ['word' => 'finis', 'meaning' => 'end-limit'],
    ['word' => 'firmus', 'meaning' => 'firm'],
    ['word' => 'fiscus', 'meaning' => 'basket'],
    ['word' => 'fistula', 'meaning' => 'pipe-tube'],
    ['word' => 'flaccus', 'meaning' => 'flabby'],
    ['word' => 'flamma', 'meaning' => 'flame'],
    ['word' => 'flavus', 'meaning' => 'yellow'],
    ['word' => 'flos', 'meaning' => 'flower'],
    ['word' => 'folium', 'meaning' => 'leaf'],
    ['word' => 'follis', 'meaning' => 'bellows'],
    ['word' => 'fons', 'meaning' => 'fountain'],
    ['word' => 'foris', 'meaning' => 'outdoors'],
    ['word' => 'formella', 'meaning' => 'form-shape'],
    ['word' => 'formica', 'meaning' => 'ant'],
    ['word' => 'formus', 'meaning' => 'warm'],
    ['word' => 'fornix', 'meaning' => 'vault'],
    ['word' => 'fors', 'meaning' => 'luck'],
    ['word' => 'fortis', 'meaning' => 'strength'],
    ['word' => 'fovea', 'meaning' => 'shallow'],
    ['word' => 'frater', 'meaning' => 'brother'],
    ['word' => 'frenum', 'meaning' => 'bridle'],
    ['word' => 'frequens', 'meaning' => 'often'],
    ['word' => 'fretum', 'meaning' => 'strait'],
    ['word' => 'frigus', 'meaning' => 'cold'],
    ['word' => 'frustrum', 'meaning' => 'piece'],
    ['word' => 'frux', 'meaning' => 'fruit'],
    ['word' => 'fulvus', 'meaning' => 'tawny'],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],
    ['word' => '', 'meaning' => ''],






];